import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import PrelineScript from "@/components/PreLineScript.tsx";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Gane crack uy tín số  ",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} subpixel-antialiased`}>
                <NavBar />
                <div className="">{children}</div>
                <Footer/>
                <script src="./node_modules/preline/dist/preline.js"></script>
            </body>
            <PrelineScript />
        </html>
    );
}
